baseURL: 'https://example.org/'
languageCode: en-us
title: Jay Morelli
theme: PaperMod

params:
  profileMode:
        enabled: true
        title: " " # optional default will be site title
        # imageUrl: "img.jpg" # optional
        # imageTitle: "<title of image as alt>" # optional
        # imageWidth: 120 # custom size
        # imageHeight: 120 # custom size
        # buttons:
        #     - name: Archive
        #       url: "/archive"
menu:
  main:
    - identifier: now
      name: Now
      title: Now
      url: /now/
      weight: 1
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 10
    - identifier: blog
      name: Blog
      title: Blog
      url: /posts/
      weight: 20
permalinks:
  page:
    posts: /posts/:day/:month/:year/:slug/
  section:
    posts: /posts/
