baseURL: 'https://www.jaymorelli.me/'
languageCode: en-us
title: Jay Morelli
theme: PaperMod

params:
  env: production
  homeInfoParams:
    images:
      - "og.png"
    cover:
      image: "og.png"
  defaultTheme: dark
  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
  profileMode:
    enabled: true
    title: " " # optional default will be site title
    imageUrl: "profile_picture.png"
  socialIcons: 
    - name: github
      url: "https://github.com/jaymorelli96"
    - name: linkedin
      url: "https://www.linkedin.com/in/jaymorelli/"
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowShareButtons: false
  ShareButtons: ["linkedin", "twitter", "whatsapp", "facebook"] # To customize which share buttons to be enabled on page
  ShowToc: false
  ShowPostNavLinks: true
  disableSpecial1stPost: true

menu:
  main:
    - identifier: now
      name: /now
      title: Now
      url: /now/
      weight: 1
    - identifier: about
      name: /about
      title: About
      url: /about/
      weight: 10
    - identifier: uses
      name: /uses
      title: Uses
      url: /uses/
      weight: 20
    - identifier: blog
      name: /blog
      title: Blog
      url: /blog/
      weight: 30
permalinks:
  page:
    posts: /blog/:slug/
  section:
    posts: /blog/

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: nord
    tabWidth: 4


deployment:
  targets: 
    - name: "production"
      URL: "s3://www.jaymorelli.me?region=eu-south-2"
